// data.js — Sample trend cards & admin data
// Exposes window.TR_DATA for the prototype

const CARDS = [
  {
    id: "c01",
    title: "코스트코 떠먹는 망고푸딩",
    category: "디저트",
    timing: "green", // 지금 타도 됨
    score: 8.4,
    velocity: "+62%",
    rank: 1,
    cover: { hue: 38, sat: 92, lum: 68, label: "MANGO\nPUDDING" },
    what: "코스트코에서 파는 1.2kg짜리 떠먹는 망고푸딩. 큰 통에 숟가락 꽂아서 떠먹는 비주얼이 핵심.",
    why: "1) 큰 사이즈가 ASMR/먹방 포맷에 잘 맞음 2) '코스트코 신상' 키워드가 인스타에서 일 8.7K 게시물로 급상승 3) 가격 대비 양 콘텐츠로 재해석 가능",
    angle: "통째로 한 입 vs 정량 컵 분배 비교. 4인 가족 5일치 분량으로 푸딩 활용 레시피 시리즈도 가능.",
    hook: "이거 한 통이 다섯 명이서 못 다 먹어요",
    platform: [
      { p: "릴스", tip: "0~3초 통 크기 강조 풀샷, 5초부터 떠먹는 ASMR" },
      { p: "쇼츠", tip: "코스트코 영수증 → 푸딩 컷 → 한 숟갈, 9:16 세로컷 좋음" },
      { p: "틱톡", tip: "'한 통 다 먹기 챌린지' 포맷" },
    ],
    caution: "코스트코 매장 내 촬영은 정책상 금지. 차에서 개봉컷부터 시작 권장.",
    sources: [
      { type: "naver", label: "네이버 검색 +62% (1주)", url: "#" },
      { type: "x", label: "@food_seoul · 2.1만 좋아요", url: "#" },
      { type: "insta", label: "#코스트코신상 · 8.7K 게시물", url: "#" },
    ],
    publishedAt: "오늘 09:42",
  },
  {
    id: "c02",
    title: "버터떡",
    category: "디저트",
    timing: "yellow",
    score: 6.9,
    velocity: "+24%",
    rank: 2,
    cover: { hue: 48, sat: 78, lum: 78, label: "BUTTER\nTTEOK" },
    what: "버터 한 조각을 인절미·찹쌀떡 사이에 끼워 굽거나 데워 먹는 변형 떡. 짭짤+고소+쫀득 조합.",
    why: "유튜브 '하루한끼' 채널 영상 이후 검색량 점진 상승. 단, 상승세가 1주 단위로 꺾이는 중 — 빠르게 타야 함.",
    angle: "한 입 베어 무는 클로즈업, 버터 녹는 단면 부각. 짠/단 페어링 시리즈의 첫 화로도 좋음.",
    hook: "떡인데 짭짤해서 한 박스 다 먹었어요",
    platform: [
      { p: "릴스", tip: "버터 자르는 컷 → 떡 가르는 컷 → 단면, 3컷 리듬" },
      { p: "쇼츠", tip: "전자레인지 30초 vs 팬에 굽기 비교 포맷" },
    ],
    caution: "특정 브랜드 떡 협찬 트윗이 다수 — 광고로 오해되지 않게 자기 멘트 추가.",
    sources: [
      { type: "naver", label: "네이버 +24%", url: "#" },
      { type: "x", label: "@dessert_log · 8.3K", url: "#" },
    ],
    publishedAt: "오늘 09:38",
  },
  {
    id: "c03",
    title: "얼먹젤리",
    category: "디저트",
    timing: "green",
    score: 8.1,
    velocity: "+89%",
    rank: 3,
    cover: { hue: 200, sat: 72, lum: 70, label: "FROZEN\nJELLY" },
    what: "젤리를 얼려서 먹는 신규 식감 트렌드. 편의점 트레비·왕꿈틀이 등 기존 제품을 -18°C에서 4시간 이상.",
    why: "초여름 진입과 동시에 X 음식 큐레이터 12개 계정에서 동시 언급. 인스타 #얼먹젤리 게시물 24시간 내 +340%.",
    angle: "얼리기 전후 비교 컷, 깨물 때 '바삭' 효과음. 편의점별 추천 젤리 5종 랭킹.",
    hook: "젤리를 4시간 얼리면 식감이 바뀌어요",
    platform: [
      { p: "릴스", tip: "얼린 젤리 깨무는 소리 강조, 마이크 가까이" },
      { p: "쇼츠", tip: "GS25/CU/세븐 3사 비교 컷" },
      { p: "틱톡", tip: "#frozenjelly 영문 태그 같이 — 해외 수요" },
    ],
    caution: "치아 시린 사람 주의 멘트 1줄 필수.",
    sources: [
      { type: "naver", label: "네이버 +89%", url: "#" },
      { type: "x", label: "@snack_kr · 1.4만", url: "#" },
      { type: "insta", label: "#얼먹젤리 +340%", url: "#" },
    ],
    publishedAt: "오늘 09:35",
  },
  {
    id: "c04",
    title: "두쫀쿠",
    category: "디저트",
    timing: "red",
    score: 4.2,
    velocity: "-12%",
    rank: 8,
    cover: { hue: 18, sat: 65, lum: 60, label: "DUJJON\nKKU" },
    what: "두꺼운 + 쫀득한 쿠키 (두쫀쿠). 베이커리 카페 신메뉴 코너에 동시 등장한 NY스타일 쿠키 변형.",
    why: "이미 3주 전 정점. 현재 X 언급량 -12%, 베이커리 카페 신메뉴에서 빠지는 중. 굳이 지금 찍기엔 노출 약함.",
    angle: "타고 싶다면 '두쫀쿠 끝물 솔직 리뷰' 같은 반대 포지션. 일반 포맷은 비추.",
    hook: "솔직히 두쫀쿠는 이제 좀… (라고 말하면 안 되는 이유)",
    platform: [
      { p: "릴스", tip: "추천하지 않음. 굳이라면 회고/리뷰 포맷" },
    ],
    caution: "끝물 표시 있음. 사용자에게 정직하게.",
    sources: [
      { type: "naver", label: "네이버 -12%", url: "#" },
      { type: "x", label: "최근 2주 언급 감소", url: "#" },
    ],
    publishedAt: "오늘 09:32",
  },
  {
    id: "c05",
    title: "초코바게트",
    category: "디저트",
    timing: "yellow",
    score: 7.2,
    velocity: "+31%",
    rank: 4,
    cover: { hue: 22, sat: 45, lum: 38, label: "CHOCO\nBAGUETTE" },
    what: "바게트 안에 다크 초콜릿 통째로 박혀 있는 프랑스풍 베이커리 신상. 파리바게뜨·뚜레쥬르 동시 출시.",
    why: "프랜차이즈 두 곳 동시 출시 → 자연스러운 비교 콘텐츠 수요. 단 신상 카테고리 자체가 1주 수명.",
    angle: "두 브랜드 블라인드 비교 (가격/중량/초콜릿 양/식감). 점수표 인서트.",
    hook: "파바 vs 뚜쥬, 어디 초코바게트가 진짜",
    platform: [
      { p: "릴스", tip: "쪼개는 단면 컷 필수. 초콜릿 노출량 비교" },
      { p: "쇼츠", tip: "9:16, 두 제품 좌우 분할 화면" },
    ],
    caution: "양사 PR팀에서 콘텐츠 모니터링 중. 객관적 톤 유지.",
    sources: [
      { type: "naver", label: "네이버 +31%", url: "#" },
      { type: "x", label: "@bakery_pick · 6.2K", url: "#" },
    ],
    publishedAt: "오늘 09:28",
  },
  {
    id: "c06",
    title: "칠리스 치즈스틱",
    category: "식당",
    timing: "green",
    score: 8.7,
    velocity: "+74%",
    rank: 5,
    cover: { hue: 12, sat: 78, lum: 52, label: "CHILI'S\nSTICKS" },
    what: "칠리스 시즈널 메뉴 치즈스틱. 5월 한정 출시, 평소 안 파는 메뉴라 희소성 콘텐츠 가능.",
    why: "한정 메뉴 + 미국 외식 브랜드 한국 재진입 화제성 결합. 인스타 #칠리스 게시물 1주 +218%.",
    angle: "메뉴 비주얼 풀샷 → 가르는 컷 → 치즈 늘어남. 1인 vs 2인 양 비교.",
    hook: "칠리스 5월만 파는 메뉴인데 사람들 모름",
    platform: [
      { p: "릴스", tip: "치즈 늘어나는 슬로우모션 필수. 9:16 세로컷" },
      { p: "쇼츠", tip: "매장 들어가는 첫 컷 → 메뉴판 클로즈업 → 음식" },
    ],
    caution: "특정 지점만 운영하는 시즈널일 수 있음. 지점 정보 자막으로.",
    sources: [
      { type: "naver", label: "네이버 +74%", url: "#" },
      { type: "x", label: "@chains_kr · 9.1K", url: "#" },
      { type: "insta", label: "#칠리스 +218%", url: "#" },
    ],
    publishedAt: "오늘 09:25",
  },
  {
    id: "c07",
    title: "촉촉한 황치즈칩",
    category: "편의점",
    timing: "yellow",
    score: 6.4,
    velocity: "+18%",
    rank: 6,
    cover: { hue: 50, sat: 88, lum: 60, label: "MOIST\nCHEESE" },
    what: "GS25 한정 출시 황치즈맛 감자칩의 변형. 일반 감자칩과 달리 식감이 촉촉/말랑하게 조정된 신제품.",
    why: "감자칩에서 '바삭' 대신 '촉촉'을 만든다는 점이 화제. 다만 호불호 콘텐츠라 양극 반응.",
    angle: "기존 황치즈칩 vs 신제품 비교. 식감 묘사가 핵심.",
    hook: "감자칩인데 촉촉하다는 게 말이 됩니까",
    platform: [
      { p: "릴스", tip: "씹는 소리 ASMR, 일반 vs 신제품 좌우 분할" },
    ],
    caution: "GS25 한정 — 다른 편의점 검색 유입 실망 방지 자막.",
    sources: [
      { type: "naver", label: "네이버 +18%", url: "#" },
      { type: "x", label: "@cvs_news · 4.4K", url: "#" },
    ],
    publishedAt: "오늘 09:22",
  },
  {
    id: "c08",
    title: "동결건조 디저트",
    category: "디저트",
    timing: "green",
    score: 7.8,
    velocity: "+45%",
    rank: 7,
    cover: { hue: 320, sat: 35, lum: 78, label: "FREEZE\nDRIED" },
    what: "딸기/요거트/케이크를 동결건조한 가벼운 식감 디저트. 다이소·올영에서 동시 진열 시작.",
    why: "다이소 신상 + 다이어트 키워드 결합. 4월 말부터 X·인스타에서 안정적 상승세.",
    angle: "원본 vs 동결건조 식감/맛 비교. 무게 비교 (10g 봉지에 딸기 한 팩).",
    hook: "딸기 한 팩이 봉지에 다 들어가요 (10g)",
    platform: [
      { p: "릴스", tip: "원본 딸기와 동결건조 좌우 비교, 가벼움 강조 컷" },
      { p: "쇼츠", tip: "가격표 클로즈업 → 시식 → 짧은 멘트" },
    ],
    caution: "수분 적어 목멤 — 음료와 함께 멘트.",
    sources: [
      { type: "naver", label: "네이버 +45%", url: "#" },
      { type: "x", label: "@daiso_pick · 5.8K", url: "#" },
    ],
    publishedAt: "오늘 09:18",
  },
];

// Realtime trend ranking (similar to 실시간 검색어)
const REALTIME = [
  { rank: 1, kw: "얼먹젤리", delta: "▲ 4", deltaType: "up" },
  { rank: 2, kw: "코스트코 망고푸딩", delta: "NEW", deltaType: "new" },
  { rank: 3, kw: "칠리스 치즈스틱", delta: "▲ 2", deltaType: "up" },
  { rank: 4, kw: "버터떡", delta: "▼ 1", deltaType: "down" },
  { rank: 5, kw: "초코바게트", delta: "—", deltaType: "same" },
  { rank: 6, kw: "동결건조", delta: "▲ 3", deltaType: "up" },
  { rank: 7, kw: "촉촉한 황치즈칩", delta: "▼ 2", deltaType: "down" },
  { rank: 8, kw: "두쫀쿠", delta: "▼ 5", deltaType: "down" },
  { rank: 9, kw: "녹차 크림 마들렌", delta: "NEW", deltaType: "new" },
  { rank: 10, kw: "콜드브루 젤리", delta: "▲ 1", deltaType: "up" },
];

const CATEGORIES = ["전체", "디저트", "식당", "편의점", "음료"];

// Admin: candidate keywords pending review
const CANDIDATES = [
  {
    id: "k001",
    keyword: "녹차 크림 마들렌",
    category: "디저트",
    sources: { x: 14, insta: 73, naver: "+58%" },
    firstSeen: "2시간 전",
    confidence: 0.82,
    note: "스타벅스 신상 + 개인 베이커리 다수 동시 출시",
  },
  {
    id: "k002",
    keyword: "콜드브루 젤리",
    category: "음료",
    sources: { x: 8, insta: 41, naver: "+34%" },
    firstSeen: "5시간 전",
    confidence: 0.71,
    note: "메가커피 시즈널, 4월 말 진입",
  },
  {
    id: "k003",
    keyword: "스타벅스 우베라떼",
    category: "음료",
    sources: { x: 22, insta: 0, naver: "+103%" },
    firstSeen: "1시간 전",
    confidence: 0.91,
    note: "5/20 출시 예정. 사전 노출 강함",
  },
  {
    id: "k004",
    keyword: "에디션덴마크 푸딩",
    category: "디저트",
    sources: { x: 3, insta: 18, naver: "+12%" },
    firstSeen: "1일 전",
    confidence: 0.42,
    note: "신호 약함 — 더 관찰 필요",
  },
  {
    id: "k005",
    keyword: "마라 떡볶이",
    category: "식당",
    sources: { x: 0, insta: 96, naver: "+8%" },
    firstSeen: "6시간 전",
    confidence: 0.55,
    note: "X에서 안 잡힘 — 인스타 위주",
  },
  {
    id: "k006",
    keyword: "솔티드 카라멜 빙수",
    category: "디저트",
    sources: { x: 17, insta: 52, naver: "+41%" },
    firstSeen: "3시간 전",
    confidence: 0.78,
    note: "여름 시즌 진입 — 시기 좋음",
  },
];

const ACCOUNTS = [
  { handle: "@food_seoul", trust: 5, freq: "4h", lastCheck: "12분 전", category: "디저트/카페", enabled: true },
  { handle: "@dessert_log", trust: 4, freq: "4h", lastCheck: "28분 전", category: "디저트", enabled: true },
  { handle: "@snack_kr", trust: 5, freq: "4h", lastCheck: "5분 전", category: "스낵/편의점", enabled: true },
  { handle: "@bakery_pick", trust: 4, freq: "4h", lastCheck: "1시간 전", category: "베이커리", enabled: true },
  { handle: "@cvs_news", trust: 4, freq: "12h", lastCheck: "3시간 전", category: "편의점", enabled: true },
  { handle: "@chains_kr", trust: 3, freq: "12h", lastCheck: "4시간 전", category: "프랜차이즈", enabled: true },
  { handle: "@daiso_pick", trust: 3, freq: "12h", lastCheck: "6시간 전", category: "다이소/소품샵", enabled: true },
  { handle: "@cafe_2025", trust: 3, freq: "12h", lastCheck: "8시간 전", category: "카페", enabled: false },
  { handle: "@menu_radar", trust: 2, freq: "12h", lastCheck: "—", category: "외식", enabled: false },
];

const BLOCKLIST = [
  "광고", "협찬", "이벤트", "쿠폰", "신규가입", "1+1",
];

const STATS = {
  todayPublished: 8,
  todayDraft: 3,
  candidates: 6,
  collectedX: 142,
  collectedNaver: 24,
  apiUsage: { used: 8420, limit: 15000 },
  weekly: [4, 6, 5, 8, 7, 9, 8], // mon~sun
};

window.TR_DATA = { CARDS, REALTIME, CATEGORIES, CANDIDATES, ACCOUNTS, BLOCKLIST, STATS };
