// Trend Radar — sample data
// 16 trend cards based on user-provided keywords, plus categories,
// candidates queue for admin, and dashboard metrics.

const CATEGORIES = [
  { id: 'all',       label: '전체' },
  { id: 'dessert',   label: '디저트' },
  { id: 'bakery',    label: '베이커리' },
  { id: 'snack',     label: '과자/스낵' },
  { id: 'restaurant',label: '식당' },
  { id: 'cvs',       label: '편의점' },
  { id: 'drink',     label: '음료' },
  { id: 'meme',      label: '밈/유행어' },
];

// timing: 'go' | 'soon' | 'late'
// score 0-100 (manual + datalab combined)
// trend: small array for sparkline
// sources: { x?, datalab?, instagram? } urls (mocked)
const CARDS = [
  {
    id: 'mango',
    title: '코스트코 떠먹는 망고푸딩',
    category: 'dessert',
    timing: 'go',
    score: 92,
    delta: '+148%',
    rank: 1, prevRank: 4,
    trend: [3,5,4,8,12,22,38,55,78,92],
    snippet: '코스트코 PB 신상. 4일 만에 인스타 게시물 1.2만건 돌파, 아직 유튜브 쇼츠는 비어있음.',
    publishedAt: '오늘 09:42',
    what: '코스트코가 새로 출시한 떠먹는 망고푸딩(900g, 13,990원). 두꺼운 푸딩 위에 망고 큐브가 올라가 있어 \"떠먹기\"가 핵심.',
    why: 'X와 인스타에서 코스트코 후기 계정들이 동시 발견 후 \"줄 서서 산다\"는 인증이 4일째 누적. 네이버 검색량이 6일 만에 14배 상승했고, 비슷한 \"코스트코 PB 디저트\" 인기 패턴 재현 중.',
    timingNote: '경쟁 콘텐츠 12편(쇼츠 기준). 아직 1만 조회 이상이 3편밖에 없어 진입 여지 충분.',
    angles: [
      '코스트코 vs 편의점 망고푸딩 4종 블라인드',
      '한 통 다 비우기 ASMR (900g 챌린지)',
      '망고푸딩 + 우유 / 연유 / 시리얼 조합 실험',
      '오픈런 후기 (인기 매장 오전 9시 30분)',
    ],
    hook: '"코스트코에서 13,990원짜리 푸딩 샀는데… 한 숟갈에 망고가 박혀있음"',
    platformTips: [
      { p: 'Reels',  t: '첫 컷은 뚜껑 여는 순간. 자막은 가격 강조.' },
      { p: 'Shorts', t: 'ASMR 트랙 추천. 떠먹는 소리만으로 15초 채워도 됨.' },
      { p: 'TikTok', t: '\"코스트코 신상\" 해시태그 + \"먹방 ASMR\" 병행.' },
    ],
    cautions: '코스트코 제휴/광고로 오인될 수 있음. 가격 변동/품절 가능성 멘트 필요.',
    sources: [
      { kind: 'X',           label: '@costco_kr_pick · 4일 전',     url: '#' },
      { kind: 'X',           label: '@nado_costco · 3일 전',        url: '#' },
      { kind: 'Datalab',     label: '네이버 검색량 7일 +148%',       url: '#' },
      { kind: 'Instagram',   label: '#코스트코망고푸딩 12,400건',     url: '#' },
    ],
  },
  {
    id: 'butter-tteok',
    title: '버터떡',
    category: 'dessert',
    timing: 'go',
    score: 84,
    delta: '+96%',
    rank: 2, prevRank: 5,
    trend: [2,3,5,9,14,22,30,48,66,84],
    snippet: '제주 디저트 카페발. 갓 구운 가래떡에 차가운 버터를 끼워 먹는 포맷.',
    publishedAt: '오늘 09:42',
    what: '구운 가래떡 사이에 차가운 무염버터(또는 가염)를 끼워 먹는 디저트. 제주 한 카페에서 시작 → 서울 디저트 카페 2곳이 메뉴 도입.',
    why: '\"버터 + 한국 디저트\" 조합이 작년 약과·앙버터에 이어 또 한 번 터지는 신호. X 인플루언서 3명이 같은 주에 \"이게 왜 이렇게 맛있냐\" 톤으로 올림.',
    timingNote: '서울 도입 매장 2곳 → 1주 내 5곳 이상 예상. 홈베이킹 버전 콘텐츠 거의 없음.',
    angles: [
      '집에서 만드는 버터떡 (가래떡 + 버터)',
      '버터떡 vs 앙버터 vs 약과 비교',
      '실제 매장 줄 후기 (제주/서울)',
      '간장·꿀·시나몬 버전 응용',
    ],
    hook: '"가래떡에 차가운 버터를 끼웠더니… 제주에서 이거 먹으려고 줄 섭니다"',
    platformTips: [
      { p: 'Reels',  t: '버터가 녹기 시작하는 0.5초 슬로모션.' },
      { p: 'Shorts', t: '버터 자르는 소리 → 한입 → 표정.' },
    ],
    cautions: '카페 상호 노출 시 동의 받기. 버터 종류(가염/무염) 명확히.',
    sources: [
      { kind: 'X',         label: '@jeju_dessert · 6일 전',     url: '#' },
      { kind: 'Datalab',   label: '검색량 7일 +96%',            url: '#' },
      { kind: 'Instagram', label: '#버터떡 3,210건',             url: '#' },
    ],
  },
  {
    id: 'ulmuk',
    title: '얼먹젤리',
    category: 'snack',
    timing: 'go',
    score: 78,
    delta: '+73%',
    rank: 3, prevRank: 9,
    trend: [4,5,6,8,12,20,32,46,60,78],
    snippet: '얼려 먹는 젤리. 편의점 신상 + 홈메이드 인기 동시 상승.',
    publishedAt: '오늘 09:42',
    what: '시판 젤리(왕꿈틀이/하리보 등)를 통째로 얼려 먹는 트렌드. 편의점 신상 \"얼먹전용\" 젤리도 출시됨.',
    why: '여름 진입 시즌성 + \"식감 챌린지\" 카테고리에 끼어듦. 1020 X에서 \"이가 시려도 멈출 수 없다\" 톤.',
    timingNote: '쇼츠 카테고리에 30편 이상 등장. 이미 큰 채널이 두 곳 진입. 빠르면 빠를수록 좋음.',
    angles: [
      '편의점 젤리 10종 얼려서 식감 랭킹',
      '얼리는 시간별 식감 변화 (1h vs 6h vs 12h)',
      '얼먹젤리 + 탄산수 폭탄 실험',
    ],
    hook: '"젤리를 12시간 얼리면 어떻게 될까?"',
    platformTips: [
      { p: 'Shorts', t: '얼린 젤리 \"빠각\" 소리 → 가장 강한 훅.' },
      { p: 'Reels',  t: '온도계 그래픽 오버레이.' },
    ],
    cautions: '치아 시림/충치 주의 경고 필요.',
    sources: [
      { kind: 'X',         label: '@conv_pick · 5일 전',  url: '#' },
      { kind: 'Datalab',   label: '검색량 +73%',          url: '#' },
    ],
  },
  {
    id: 'doojonku',
    title: '두쫀쿠',
    category: 'bakery',
    timing: 'soon',
    score: 71,
    delta: '+34%',
    rank: 4, prevRank: 2,
    trend: [10,20,40,55,68,74,72,71,70,71],
    snippet: '두 겹 쫀득 쿠키. 정점에 도달, 24~48시간 안에 찍어야 안전.',
    publishedAt: '오늘 09:42',
    what: '두 겹으로 구운 쫀득한 쿠키. 카페 \"수퍼커먼\"발로 시작해 디저트 카페 8곳 이상 도입.',
    why: '\"쫀득 쿠키\" 카테고리의 신선한 변주. 식감 동영상이 알고리즘 친화적.',
    timingNote: '⚠ 검색량 그래프가 평탄해지기 시작. 큰 채널 7편 진입. 48시간 안에 찍지 않으면 끝물.',
    angles: [
      '집에서 만드는 두쫀쿠 레시피',
      '두쫀쿠 카페 4곳 비교',
      '두쫀쿠 vs 일반 쫀쿠 식감 단면 비교',
    ],
    hook: '"카페 디저트 1위 두쫀쿠… 집에서 만들 수 있을까?"',
    platformTips: [
      { p: 'Reels',  t: '쿠키 뜯는 단면 슬로모션이 핵심.' },
    ],
    cautions: '이미 큰 채널 영상이 노출 중. 차별 포인트 없으면 진입 비추.',
    sources: [
      { kind: 'X',         label: '@cafe_seoul · 9일 전', url: '#' },
      { kind: 'Datalab',   label: '검색량 +34% (둔화)',    url: '#' },
    ],
  },
  {
    id: 'choco-baguette',
    title: '초코바게트',
    category: 'bakery',
    timing: 'go',
    score: 81,
    delta: '+88%',
    rank: 5, prevRank: 11,
    trend: [2,3,4,6,12,22,38,55,72,81],
    snippet: '바게트 속에 초콜릿 가나슈. 파리바게뜨 시즌 한정 출시 + 홈베이킹 확산.',
    publishedAt: '오늘 09:42',
    what: '겉은 바삭한 바게트, 속은 초콜릿 가나슈로 채운 빵. 파리바게뜨 시즌 한정 메뉴로 출시 후 카페·홈베이킹 양쪽에서 확산.',
    why: '시판 + 홈베이킹 두 갈래로 동시에 떠 노출 폭이 큼. 단면 컷이 매우 강함.',
    timingNote: '큰 채널 진입 2편. 4~5일 안에 찍는 게 안전.',
    angles: [
      '파바 초코바게트 vs 홈베이킹 비교',
      '초코바게트 + 우유 / 아이스크림 조합',
      '단면 ASMR (가나슈 흘러내림)',
    ],
    hook: '"바게트를 자르니까 초콜릿이 흐른다"',
    platformTips: [
      { p: 'Reels', t: '단면 컷이 모든 것. 0.5초 슬로모션.' },
    ],
    cautions: '파바 광고로 오인될 수 있음. \"개인 후기\" 명시.',
    sources: [
      { kind: 'Datalab',   label: '검색량 +88%',       url: '#' },
      { kind: 'Instagram', label: '#초코바게트 8,940건', url: '#' },
    ],
  },
  {
    id: 'chilis',
    title: '칠리스 치즈스틱',
    category: 'restaurant',
    timing: 'go',
    score: 76,
    delta: '+62%',
    rank: 6, prevRank: 14,
    trend: [3,4,5,7,10,18,28,42,58,76],
    snippet: '칠리스 재오픈 발 트래픽. 시그니처 치즈스틱이 단일 메뉴로 가장 많이 언급.',
    publishedAt: '오늘 09:42',
    what: '미국 캐주얼 다이닝 \"Chili\'s\" 한국 재오픈. 시그니처 사이드인 치즈스틱이 \"꼭 시켜야 하는 메뉴\"로 언급 1위.',
    why: '오픈런 트래픽 + 미국 체인 향수 콘텐츠가 동시에 묶임. \"한국 한정\"이 아닌 \"미국 그대로\"라는 점이 강조 포인트.',
    timingNote: '오픈 후 5일차. 다음 주말까지가 황금 타이밍.',
    angles: [
      '칠리스 한국 vs 미국 메뉴 비교',
      '치즈스틱 + 자체 디핑소스 4종',
      '오픈런 줄 서기 후기 (대기 시간)',
    ],
    hook: '"한국에 다시 들어온 칠리스, 진짜 미국 맛 그대로일까?"',
    platformTips: [
      { p: 'Reels',  t: '치즈스틱 늘어나는 컷.' },
      { p: 'TikTok', t: '"chilis korea reopen" 영어 자막 병행.' },
    ],
    cautions: '브랜드 직접 협찬으로 오해 가능. \"방문 후기\" 명시.',
    sources: [
      { kind: 'X',         label: '@chilis_kr_open · 5일 전', url: '#' },
      { kind: 'Datalab',   label: '검색량 +62%',              url: '#' },
    ],
  },
  {
    id: 'hwang-chip',
    title: '촉촉한 황치즈칩',
    category: 'cvs',
    timing: 'soon',
    score: 64,
    delta: '+28%',
    rank: 7, prevRank: 3,
    trend: [12,28,48,60,66,68,65,64,63,64],
    snippet: '편의점 신상. 정점 근처, 진입 시 빠른 마감 필요.',
    publishedAt: '오늘 09:42',
    what: 'GS25 신상 과자. 일반 황치즈칩과 달리 \"촉촉한\" 식감을 내세움.',
    why: '\"바삭한 칩이 촉촉할 수 있나?\" 의문이 콘텐츠 훅으로 강함.',
    timingNote: '⚠ 검색량 평탄화. 큰 채널 5편 진입. 36시간 안에 마감 권장.',
    angles: [
      '\"촉촉한\" vs 일반 황치즈칩 비교',
      '편의점 황치즈 신상 4종 블라인드',
    ],
    hook: '"\'촉촉한 황치즈칩\'… 이 표현이 가능해요?"',
    platformTips: [
      { p: 'Shorts', t: '봉지 뜯는 소리 + 첫 한 입 식감.' },
    ],
    cautions: '편의점 협찬으로 오인 주의.',
    sources: [
      { kind: 'X',       label: '@gs25_pick · 8일 전', url: '#' },
      { kind: 'Datalab', label: '검색량 +28% (둔화)',   url: '#' },
    ],
  },
  {
    id: 'setlog',
    title: '셋로그',
    category: 'meme',
    timing: 'late',
    score: 38,
    delta: '-12%',
    rank: 8, prevRank: 1,
    trend: [40,68,82,90,85,72,60,52,44,38],
    snippet: '\"세 명이 같이 사는 일상\" 브이로그 포맷. 이미 큰 채널이 다 점령.',
    publishedAt: '오늘 09:42',
    what: '셋이 같이 사는 일상 브이로그 포맷. 인물 셋 X 일상 = 셋로그.',
    why: '브이로그 안에 인물 캐스팅이 들어가 알고리즘 친화적. 단, 큰 채널이 모두 진입함.',
    timingNote: '🚫 끝물. 새 진입 시 노출 안 나옴. 이미 본인이 셋이 사는 경우만 시도 권장.',
    angles: [
      '(권장 안 함) 진입 시 차별 포인트 필요',
    ],
    hook: '— (진입 비권장)',
    platformTips: [
      { p: '—', t: '본인만의 캐릭터 차별화 없으면 비추.' },
    ],
    cautions: '큰 채널 점유율 70% 이상. 신규 진입 어려움.',
    sources: [
      { kind: 'Datalab', label: '검색량 -12% (하락 중)', url: '#' },
    ],
  },
  {
    id: 'saeklog',
    title: '색로그',
    category: 'meme',
    timing: 'go',
    score: 70,
    delta: '+58%',
    rank: 9, prevRank: 18,
    trend: [3,4,6,10,18,30,45,58,66,70],
    snippet: '하루를 한 가지 색으로만 채우는 브이로그 포맷. 시작 단계.',
    publishedAt: '오늘 09:42',
    what: '하루의 옷·음식·물건을 한 가지 색으로만 채우는 브이로그 포맷. \"셋로그\" 다음 진화 형태.',
    why: '인스타 그리드 친화적 미장센. 시작한 큰 채널이 아직 2개뿐.',
    timingNote: '큰 채널 진입 2개. 1~2주 안이 황금기.',
    angles: [
      '\"하루 종일 노란색만\" 챌린지',
      '색로그 음식 편 (한 가지 색 메뉴)',
      '색로그 패션 + 음식 합본',
    ],
    hook: '"오늘 하루 노란색만 먹고 입으면 어떻게 될까?"',
    platformTips: [
      { p: 'Reels',  t: '그리드 미장센이 핵심. 정사각 컷 다수.' },
    ],
    cautions: '색 통일을 무리하게 하면 어색함. 자연스러운 일상 톤 유지.',
    sources: [
      { kind: 'X',       label: '@vlog_curate · 4일 전', url: '#' },
      { kind: 'Datalab', label: '검색량 +58%',           url: '#' },
    ],
  },
  {
    id: 'baseball-ai',
    title: 'AI 야구 중계샷',
    category: 'meme',
    timing: 'go',
    score: 73,
    delta: '+82%',
    rank: 10, prevRank: 22,
    trend: [1,2,3,5,10,20,35,52,66,73],
    snippet: 'AI로 만든 \"야구 중계 캡처\" 짤. 음식 콘텐츠 오프닝 훅 활용 사례 증가.',
    publishedAt: '오늘 09:42',
    what: 'ChatGPT/Midjourney로 만든 가짜 야구 중계 캡처. \"X구단 OO선수 9회말 결승타\" 같은 문장이 박힌 단일 컷.',
    why: '음식 콘텐츠 제작자들이 \"내가 만든 디저트가 결승타급\" 식의 오프닝 훅으로 변형 사용 중.',
    timingNote: '음식 카테고리에서 응용 사례 거의 없음. 빠르면 빠를수록 좋음.',
    angles: [
      '음식 콘텐츠 오프닝을 AI 중계샷으로',
      '\"오늘의 디저트 MVP\" 시리즈 포맷',
    ],
    hook: '오프닝 1초: \"9회말 2아웃, 만루\" → 컷 → 디저트 등장',
    platformTips: [
      { p: 'Reels',  t: '오프닝 0~1초만 AI 컷. 본편은 일반 촬영.' },
    ],
    cautions: '특정 실명 선수 차용 시 초상권 이슈. 가상 이름 사용 권장.',
    sources: [
      { kind: 'X', label: '@ai_meme · 3일 전', url: '#' },
    ],
  },
  {
    id: 'salmokji',
    title: '살목지',
    category: 'meme',
    timing: 'soon',
    score: 55,
    delta: '+12%',
    rank: 11, prevRank: 6,
    trend: [10,25,42,55,60,58,56,55,54,55],
    snippet: '\"살이 목구멍에 지나간다\" 줄임말. 먹방 자막용으로 정착 중.',
    publishedAt: '오늘 09:42',
    what: '\"살이 목구멍에 지나간다\"의 줄임말. 먹방 자막/오버레이로 사용.',
    why: '먹방 카테고리에 자막용으로 안착 가능성. 하지만 사용 빈도가 빠르게 늘어 신선도 짧음.',
    timingNote: '⚠ 자막 트렌드는 수명이 짧음 (2~3주). 지금 안 쓰면 늦음.',
    angles: [
      '자막 오버레이 1초 노출용',
    ],
    hook: '먹방 중 자막으로 한 번만 등장',
    platformTips: [
      { p: 'Shorts', t: '자막으로만 사용. 메인 포맷화 비추.' },
    ],
    cautions: '먹방 메인 컨셉으로 잡으면 식상해질 위험.',
    sources: [
      { kind: 'X', label: '@meokbang_meme · 1주 전', url: '#' },
    ],
  },
  {
    id: 'nyanyanyang',
    title: '냐냐냥',
    category: 'meme',
    timing: 'late',
    score: 32,
    delta: '-22%',
    rank: 12, prevRank: 7,
    trend: [50,72,86,88,80,68,54,44,38,32],
    snippet: '고양이 의성어. 이미 광고에 사용될 정도로 끝물.',
    publishedAt: '오늘 09:42',
    what: '고양이 의성어 \"냐냐냥\"이 X 짤로 확산되었던 트렌드.',
    why: '— (이미 광고에 사용. 끝물 신호)',
    timingNote: '🚫 광고 등장 = 끝. 새 진입 권장 안 함.',
    angles: ['(진입 비권장)'],
    hook: '—',
    platformTips: [{ p: '—', t: '비권장.' }],
    cautions: '광고 카피로 이미 사용됨. 끝물.',
    sources: [
      { kind: 'Datalab', label: '검색량 -22%', url: '#' },
    ],
  },
  {
    id: 'kim-dh',
    title: '김동현 / 스트롱 스트롱',
    category: 'meme',
    timing: 'late',
    score: 28,
    delta: '-30%',
    rank: 13, prevRank: 8,
    trend: [60,80,88,80,68,54,42,34,30,28],
    snippet: '격투기 출신 인물 밈. 이미 일반 광고에 등장.',
    publishedAt: '오늘 09:42',
    what: '"스트롱 스트롱" 어록 변형 밈. 음식 콘텐츠 \"강력한 맛\" 묘사로 응용되던 흐름.',
    why: '— (이미 광고/대중매체 진입)',
    timingNote: '🚫 끝물.',
    angles: ['(비권장)'],
    hook: '—',
    platformTips: [{ p: '—', t: '비권장.' }],
    cautions: '광고/예능 노출로 신선도 소진.',
    sources: [
      { kind: 'Datalab', label: '검색량 -30%', url: '#' },
    ],
  },
  {
    id: 'longflight',
    title: '장시간 비행 밈',
    category: 'meme',
    timing: 'soon',
    score: 58,
    delta: '+18%',
    rank: 14, prevRank: 10,
    trend: [12,26,40,52,58,60,58,56,55,58],
    snippet: '\"이게 12시간 비행한 사람의 표정\"형 자막. 먹방·요리 응용 가능.',
    publishedAt: '오늘 09:42',
    what: '\"이게 12시간 비행한 사람의 표정\" 같은 자막 포맷.',
    why: '\"이게 X한 사람의 ___\" 변형이 음식에 잘 맞음 (\"이게 5일 굶은 사람의 폭식\").',
    timingNote: '자막 변형 트렌드. 2주 안에 사용 권장.',
    angles: [
      '\"이게 야식 참은 사람의 새벽 라면\"',
      '\"이게 다이어트 7일차의 폭식\"',
    ],
    hook: '자막 1줄로 첫 1.5초 채움',
    platformTips: [
      { p: 'Reels', t: '자막은 가운데 굵게 1줄.' },
    ],
    cautions: '자막 본문 표절 주의 (원본과 다르게).',
    sources: [
      { kind: 'X', label: '@flight_meme · 2주 전', url: '#' },
    ],
  },
  {
    id: 'ganbare',
    title: '간바레 챌린지',
    category: 'meme',
    timing: 'go',
    score: 68,
    delta: '+44%',
    rank: 15, prevRank: 24,
    trend: [5,8,12,18,28,40,52,60,65,68],
    snippet: '일본어 \"頑張れ\" 응원 챌린지. 요리 실패 시리즈에 응용.',
    publishedAt: '오늘 09:42',
    what: '"간바레(힘내라)" 외침을 자기 자신에게 하는 챌린지. 어려운 일에 직면한 순간 컷.',
    why: '요리/베이킹 실패 → \"간바레\" 외침 → 재시도 포맷이 잘 맞음.',
    timingNote: '음식 응용 사례 거의 없음. 진입 좋음.',
    angles: [
      '디저트 만들다 실패 → 간바레 → 재시도',
      '\"이번 주 다이어트 7일차\" 간바레',
    ],
    hook: '실패한 순간 카메라 보고 \"…간바레\"',
    platformTips: [
      { p: 'Reels', t: '실패 컷이 진짜여야 효과적.' },
    ],
    cautions: '일본어 사용에 대한 정서적 반감 가능. 가볍게.',
    sources: [
      { kind: 'X', label: '@challenge_jp · 3일 전', url: '#' },
    ],
  },
  {
    id: 'freeze-dry',
    title: '동결건조',
    category: 'snack',
    timing: 'go',
    score: 75,
    delta: '+68%',
    rank: 16, prevRank: 19,
    trend: [3,5,8,14,22,34,48,60,70,75],
    snippet: '딸기·바나나를 동결건조해서 먹는 가정용 트렌드. 가전 + 식품 양쪽 확산.',
    publishedAt: '오늘 09:42',
    what: '가정용 동결건조기로 과일/요거트/사탕을 동결건조해서 먹는 트렌드. 미국 발 → 한국 진입 중.',
    why: '식감 콘텐츠 + 가전 리뷰 둘 다 잡음. 알고리즘 친화적.',
    timingNote: '큰 채널 진입 3편. 2주 안에 시작 권장.',
    angles: [
      '편의점 사탕 10종 동결건조 식감 랭킹',
      '동결건조 vs 일반 딸기 차이',
      '동결건조 요거트 (홈메이드)',
    ],
    hook: '"딸기를 12시간 얼리면 어떻게 변할까?"',
    platformTips: [
      { p: 'Shorts', t: '\"빠삭\" 소리가 핵심.' },
    ],
    cautions: '동결건조기 가격(50만원~) 언급 시 협찬 오해 주의.',
    sources: [
      { kind: 'X',       label: '@freeze_dry_kr · 1주 전', url: '#' },
      { kind: 'Datalab', label: '검색량 +68%',             url: '#' },
    ],
  },
];

// Admin queue — pending candidate keywords awaiting review.
const CANDIDATES = [
  { id: 'c1', keyword: '버터떡', mentions: 24, datalab: 96, sources: 8,  first: '6일 전', status: 'pending', signal: 'rising' },
  { id: 'c2', keyword: '동결건조',   mentions: 18, datalab: 68, sources: 5,  first: '1주 전', status: 'pending', signal: 'rising' },
  { id: 'c3', keyword: '소금빵 바닐라', mentions: 12, datalab: 22, sources: 3,  first: '3일 전', status: 'pending', signal: 'flat' },
  { id: 'c4', keyword: '두유 라떼 신상', mentions:  9, datalab: 14, sources: 2,  first: '2일 전', status: 'pending', signal: 'flat' },
  { id: 'c5', keyword: '딸기 깍둑',   mentions: 31, datalab: 88, sources: 11, first: '4일 전', status: 'pending', signal: 'rising' },
  { id: 'c6', keyword: '미니 약과',   mentions: 17, datalab: 42, sources: 6,  first: '5일 전', status: 'pending', signal: 'flat' },
  { id: 'c7', keyword: '레몬 청',     mentions:  6, datalab:  8, sources: 2,  first: '1일 전', status: 'pending', signal: 'flat' },
  { id: 'c8', keyword: '대왕 카스테라', mentions: 14, datalab: 18, sources: 4,  first: '6일 전', status: 'pending', signal: 'falling' },
  { id: 'c9', keyword: '냐냐냥(자막)', mentions: 22, datalab: -22, sources: 7, first: '1주 전', status: 'pending', signal: 'falling' },
];

// X source accounts for admin
const ACCOUNTS = [
  { id: 'a1', handle: '@costco_kr_pick',   trust: 5, interval: '4h',  enabled: true,  posts: 142, notes: '코스트코 신상 픽업 빠름' },
  { id: 'a2', handle: '@jeju_dessert',      trust: 4, interval: '4h',  enabled: true,  posts:  88, notes: '제주 카페 발신지' },
  { id: 'a3', handle: '@cafe_seoul',        trust: 4, interval: '4h',  enabled: true,  posts:  74, notes: '' },
  { id: 'a4', handle: '@gs25_pick',         trust: 4, interval: '4h',  enabled: true,  posts:  91, notes: '편의점 신상 1차 발견' },
  { id: 'a5', handle: '@nado_costco',       trust: 5, interval: '4h',  enabled: true,  posts: 120, notes: '' },
  { id: 'a6', handle: '@conv_pick',         trust: 3, interval: '12h', enabled: true,  posts:  48, notes: '편의점 일반' },
  { id: 'a7', handle: '@ai_meme',           trust: 2, interval: '12h', enabled: true,  posts:  32, notes: '밈 일반 — 약한 신호용' },
  { id: 'a8', handle: '@chilis_kr_open',    trust: 3, interval: '12h', enabled: true,  posts:  18, notes: '오픈런 한정' },
  { id: 'a9', handle: '@food_influencer_b', trust: 1, interval: '12h', enabled: false, posts:   2, notes: '광고성 다수 — 비활성' },
];

const BLOCKLIST = [
  '협찬', '광고', '#내돈내산아님', '체험단', '주최측 제공',
];

const METRICS = {
  publishedToday: 7,
  draftQueue: 3,
  candidatesPending: 9,
  weeklyDAU: 41,
  retention7d: '34%',
  bookmarksToday: 28,
  ctr: '47%',
  feedbackThisWeek: 5,
  xUsage: { used: 9420, cap: 15000 },
};

Object.assign(window, { CATEGORIES, CARDS, CANDIDATES, ACCOUNTS, BLOCKLIST, METRICS });
